#!/bin/bash
# Runs simulation on the local machine. This script requires simulation parameters to pass and 
# optional log prefix. This is the prefix of all log files generated by the simulation.
# If this argument is provided, then all possible graphs will be generated for produced
# log files. This argument is usually the same as --simulation-out param.

if [ $# -lt 1 ]; then
  echo "Usage: $0 '<simulation args>'";
  exit 1
fi

ARGS=$1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


(set -x && java -cp "${DIR}/../../lib/*:${DIR}/../../bin/*:${DIR}/../../bin/" cws.core.simulation.Simulation $ARGS)

