#!/bin/bash
# Runs simulation on the local machine. This script requires simulation parameters to pass and 
# optional log prefix. This is the prefix of all log files generated by the simulation.
# If this argument is provided, then all possible graphs will be generated for produced
# log files. This argument is usually the same as --simulation-out param.

if [ $# -lt 1 ]; then
        echo "Usage: $0 '<simulation args>' '<optional log prefix to generate graphs for>'"
        exit 1
fi

ARGS=$1
LOG_PREFIX=$2
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


(set -x && java -cp "${DIR}/../../lib/*:${DIR}/../../bin/*:${DIR}/../../bin/" cws.core.simulation.Simulation $ARGS)

if [ $LOG_PREFIX ] ; then
  for LOG in `ls ${LOG_PREFIX}.*.log`; do
    LOG=`readlink -f "$LOG"`
    echo "Processing ${LOG}"
    (
      cd $DIR/..
      python -m log_parser.parse_experiment_log "${LOG}" "${LOG}.postlog" &&
      (
        cd visualisation
        ruby plot_gantt.rb results "${LOG}.postlog" "${LOG}.results.png"
        ruby plot_gantt.rb workflow "${LOG}.postlog" "${LOG}.workflow.png"
        ruby plot_gantt.rb storage "${LOG}.postlog" "${LOG}.storage.png"
        ruby plot_storage.rb number "${LOG}.postlog" "${LOG}.storage.number.png"
        ruby plot_storage.rb speed "${LOG}.postlog" "${LOG}.storage.speed.png"
      )
    )
  done;
fi
